//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public int ProfSubjID { get; set; }
        public int StudentID { get; set; }
        public int SemesterID { get; set; }
        public double Number { get; set; }
        public bool Final { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Professor_Subject Professor_Subject { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
